# Generated by Django 5.2.1 on 2025-05-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_financial_health_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=700000, max_digits=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='savings_amount',
            field=models.DecimalField(decimal_places=2, default=520000, max_digits=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='savings_target',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=12),
        ),
    ]
