# Generated by Django 5.2.1 on 2025-05-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_last_score_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bills_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='budget_notification_threshold',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='disposable_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='expense_anomaly_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='savings_notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekly_report_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='savings_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='savings_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
