# Generated by Django 5.2.1 on 2025-05-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_bills_notification_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='assets/default/default-avatar.png', null=True, upload_to='profile_pics/'),
        ),
    ]
