# Generated by Django 5.2.1 on 2025-05-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_savings_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
