# Generated by Django 5.2.1 on 2025-05-19 04:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_last_savings_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='details',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('savings_added', 'Savings Added'), ('expense_added', 'Expense Added'), ('bill_paid', 'Bill Paid'), ('goal_reached', 'Goal Reached'), ('budget_exceeded', 'Budget Exceeded')], default='savings_added', max_length=50),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
