#!/bin/bash

# Create 60 commits with meaningful changes

# Commit messages array
messages=(
    "Add expense category icons"
    "Update dashboard layout"
    "Fix budget calculation"
    "Add expense filtering"
    "Improve UI responsiveness"
    "Add dark mode support"
    "Fix date picker issue"
    "Update expense list styling"
    "Add category colors"
    "Improve chart animations"
    "Fix navigation bug"
    "Add expense search"
    "Update profile page"
    "Add settings screen"
    "Fix currency formatting"
    "Add expense notes field"
    "Update button styles"
    "Fix scroll behavior"
    "Add loading indicators"
    "Improve error handling"
    "Add expense sorting"
    "Update card shadows"
    "Fix text overflow"
    "Add swipe to delete"
    "Update color scheme"
    "Fix keyboard issues"
    "Add expense tags"
    "Update bottom navigation"
    "Fix state management"
    "Add expense export"
    "Update splash screen"
    "Fix memory leak"
    "Add expense import"
    "Update app icon"
    "Fix date formatting"
    "Add recurring expenses"
    "Update animations"
    "Fix layout issues"
    "Add expense reminders"
    "Update typography"
    "Fix input validation"
    "Add expense statistics"
    "Update gradient colors"
    "Fix async operations"
    "Add expense categories"
    "Update list animations"
    "Fix null safety"
    "Add expense sharing"
    "Update form validation"
    "Fix performance issues"
    "Add expense backup"
    "Update error messages"
    "Fix widget rebuild"
    "Add expense history"
    "Update padding values"
    "Fix theme switching"
    "Add expense analytics"
    "Update border radius"
    "Fix data persistence"
    "Add final polish"
)

for i in {1..60}; do
    # Make a small change to a file
    echo "// Update $i - ${messages[$((i-1))]}" >> expense_tracker_flutter/lib/main.dart
    git add expense_tracker_flutter/lib/main.dart
    git commit -m "${messages[$((i-1))]}"
done

echo "Created 60 commits!"