# This file configures the analyzer for Dart code analysis.
# https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Style rules
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    
    # Error rules
    avoid_print: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    
    # Documentation
    public_member_api_docs: false
    
    # Formatting
    curly_braces_in_flow_control_structures: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
