# Generated by Django 5.2.1 on 2025-05-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='recurrence',
            field=models.CharField(choices=[('one-time', 'One-time'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='one-time', max_length=10),
        ),
    ]
