# Generated by Django 5.2.1 on 2025-05-18 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_monthlybudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybudget',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to='budgets.budget'),
        ),
    ]
